#server:
#  port: 9191
#
#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#   gateway:
#    enabled : true 
#    routes:
#     - id:  COMPANY-SERVICE
#       uri: lb//COMPANY-SERVICE
#       predicates:
#        - Path=/company/**   
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
